language: java
services:
  - docker
cache:
  directories:
    - $HOME/.m2/repository

install:
  - mvn -Dmaven.test.skip=true clean install package

jobs:
  include:
    - stage: Unit Tests
      script: mvn test
    - stage: Integration Tests
      name: Cassandra 3.0
      script: .admin/integration_tests cassandra:3.0
    - name: Cassandra 3.11
      script: .admin/integration_tests cassandra:3.11
    - name: DSE 5.1.15
      script: .admin/integration_tests datastax/dse-server:5.1.15
    - name: DSE 6.0.8
      script: .admin/integration_tests datastax/dse-server:6.0.8
    - name: DSE 6.7.3
      script: .admin/integration_tests datastax/dse-server:6.7.3
